# fly.toml app configuration file generated for sparkling-thunder-2042 on 2023-06-21T22:30:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#x

app = "sparkling-thunder-2042"
primary_region = "lhr"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  PORT = "3001" # add this

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3001 
  processes = ["app"]